name: Deploy to Production
run-name: Deploy to Production by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and deploy with Docker Compose
        run: |
          # Próba zatrzymania i usunięcia starego kontenera (ignoruje błąd jeśli nie istnieje)
          docker compose down --remove-orphans || true
          docker rm -f rubic-cube || true
          
          # Start nowej wersji
          docker compose up -d --build
